# Generated by Django 2.2 on 2020-04-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('number', models.BigIntegerField()),
                ('product_name', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
            ],
        ),
    ]
