# Generated by Django 2.2 on 2020-04-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phone',
            new_name='Customer_Detail',
        ),
    ]
